[project]
name = "borisbikes-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "sqlitecloud>=0.0.83",
    "streamlit>=1.41.1",
]
